version: 2

build:
  commands:
    - rm -rf $READTHEDOCS_OUTPUT/html/* # Force remove any existing output to "clear cache"
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/* $READTHEDOCS_OUTPUT/html/